apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: agent-scaler
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "agent"
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: "k8s"
        organizationURLFromEnv: "AZP_URL"
        personalAccessTokenFromEnv: "AZP_TOKEN"